//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.Cash.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SC.Cash.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage accounting {
            get {
                object obj = ResourceManager.GetObject("accounting", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --declare @userId int = 117;
        ///--declare @start datetime = Cast(&apos;20200223&apos; as datetime);
        ///--declare @end datetime = Cast(&apos;20200224&apos; as datetime);
        ///--declare @month datetime = Cast(&apos;20200101&apos; as datetime);
        ///
        ///with restStart as (
        ///	select r.Acc_ID 
        ///		,(case when r.Day = @start then r.Rest_In
        ///			else r.Rest_In + r.InAmount - r.OutAmount 
        ///			end) Rest_In
        ///		,ROW_NUMBER() over (partition by r.Acc_ID order by r.Day desc) row
        ///	from Account ac
        ///		left join [User] u on u.ID = ac.User_ID
        ///		left join RestDay r on  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addfile_16x16 {
            get {
                object obj = ResourceManager.GetObject("addfile_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addfile_32x32 {
            get {
                object obj = ResourceManager.GetObject("addfile_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addnewdatasource_16x16 {
            get {
                object obj = ResourceManager.GetObject("addnewdatasource_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addnewdatasource_16x161 {
            get {
                object obj = ResourceManager.GetObject("addnewdatasource_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addnewdatasource_32x32 {
            get {
                object obj = ResourceManager.GetObject("addnewdatasource_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addnewdatasource_32x321 {
            get {
                object obj = ResourceManager.GetObject("addnewdatasource_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banknotes {
            get {
                object obj = ResourceManager.GetObject("banknotes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage bo_address {
            get {
                object obj = ResourceManager.GetObject("bo_address", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage bo_pivotchart {
            get {
                object obj = ResourceManager.GetObject("bo_pivotchart", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на declare @role_ID int;
        ///--declare @userId int = 54
        ///
        ///select  @role_ID = u.Role_ID
        ///from [User] u	
        ///where u.ID = @userId
        ///
        ///if @role_ID = 5 --manager
        ///	select distinct u.*
        ///	from [User] u
        ///		join Project pr on pr.Rukovod_ID = u.ID
        ///		join Object obj on obj.Project_ID = pr.ID
        ///	where obj.Manager_ID = @userId
        ///else if @role_ID = 4 --rukovod
        ///	select *
        ///	from [User]	where Role_ID = 6.
        /// </summary>
        internal static string Bosses {
            get {
                return ResourceManager.GetString("Bosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage business_calculator {
            get {
                object obj = ResourceManager.GetObject("business_calculator", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cancel32 {
            get {
                object obj = ResourceManager.GetObject("Cancel32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock {
            get {
                object obj = ResourceManager.GetObject("Clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_16x16 {
            get {
                object obj = ResourceManager.GetObject("close_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_32x32 {
            get {
                object obj = ResourceManager.GetObject("close_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Debt {
            get {
                object obj = ResourceManager.GetObject("Debt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --declare @rukovodId int = 0;
        ///
        ///with debts as (
        ///	select ruk.Name RukovodName
        ///		,p.ID Project_ID
        ///		,p.Name ProjectName
        ///		,manager.Name ManagerName
        ///		,obj.ID Object_ID
        ///		,obj.Address ObjectName
        ///		,Cast(DATEADD(day, 1 - Day(r.Month), r.Month) as date) Month
        ///		,(r.FactSalary - r.Paid) Debt
        ///		,r.Calculated Calculated
        ///	from ResOP r 
        ///		join Object obj on r.Object_ID = obj.ID
        ///			and obj.IsDeleted = 0 
        ///			and obj.Status = 0
        ///		left join [User] manager on obj.Manager_ID = manager.ID
        ///		join Project p on [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Debts {
            get {
                return ResourceManager.GetString("Debts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deletedatasource_16x16 {
            get {
                object obj = ResourceManager.GetObject("deletedatasource_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deletedatasource_32x32 {
            get {
                object obj = ResourceManager.GetObject("deletedatasource_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editdatasource_16x16 {
            get {
                object obj = ResourceManager.GetObject("editdatasource_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editdatasource_32x32 {
            get {
                object obj = ResourceManager.GetObject("editdatasource_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap excel {
            get {
                object obj = ResourceManager.GetObject("excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap In {
            get {
                object obj = ResourceManager.GetObject("In", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --declare
        ///--@userId int = 1
        ///
        ///select top (1) *
        ///from RequestOP
        ///where User_ID = @userId
        ///	order by DateTime desc.
        /// </summary>
        internal static string LastRequest_Out {
            get {
                return ResourceManager.GetString("LastRequest_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loadfrom_16x16 {
            get {
                object obj = ResourceManager.GetObject("loadfrom_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loadfrom_32x32 {
            get {
                object obj = ResourceManager.GetObject("loadfrom_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage mailmerge {
            get {
                object obj = ResourceManager.GetObject("mailmerge", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --declare 
        ///--@rukId int = 63
        ///
        ///select *
        ///from [User] u
        ///where exists (select o.* 
        ///			from Object o
        ///				join Project p on p.ID = o.Project_ID
        ///			where o.Manager_ID = u.ID
        ///					and p.Rukovod_ID = @rukId)
        ///order by Name.
        /// </summary>
        internal static string Managers {
            get {
                return ResourceManager.GetString("Managers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Money {
            get {
                object obj = ResourceManager.GetObject("Money", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap New {
            get {
                object obj = ResourceManager.GetObject("New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Note {
            get {
                object obj = ResourceManager.GetObject("Note", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notes_16x16 {
            get {
                object obj = ResourceManager.GetObject("notes_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notes_32x32 {
            get {
                object obj = ResourceManager.GetObject("notes_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ok {
            get {
                object obj = ResourceManager.GetObject("Ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select op.*
        ///,s.DataCreate DataCreate
        ///,f.Name FirmaName
        ///,su.Name Comment
        ///from OperationCash op
        ///	join Scheta s on op.Schet_ID = s.ID
        ///	left join Supplier su on s.Supplier_ID = su.ID
        ///	left join SCFirma f on s.Firma_ID = f.ID
        ///--where op.Status = 0.
        /// </summary>
        internal static string OperationsCash {
            get {
                return ResourceManager.GetString("OperationsCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Out {
            get {
                object obj = ResourceManager.GetObject("Out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap payment {
            get {
                object obj = ResourceManager.GetObject("payment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap recurrence_16x16 {
            get {
                object obj = ResourceManager.GetObject("recurrence_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap recurrence_32x32 {
            get {
                object obj = ResourceManager.GetObject("recurrence_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rejected {
            get {
                object obj = ResourceManager.GetObject("Rejected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Report {
            get {
                object obj = ResourceManager.GetObject("Report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportMoney {
            get {
                object obj = ResourceManager.GetObject("ReportMoney", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на declare @role_ID int
        ///--,@userId int = 1
        ///
        ///select  @role_ID = u.Role_ID
        ///from [User] u	
        ///where u.ID = @userId
        ///
        ///if @role_ID = 1 --admin
        ///	select r.*
        ///		,u.Name UserName
        ///	from RequestOP r
        ///		join [User] u on u.ID = r.User_ID
        ///
        ///else if @role_ID = 6 --director
        ///	select r.*
        ///		,u.Name UserName
        ///	from RequestOP r
        ///		join [User] u on u.ID = r.User_ID
        ///		where u.Role_ID = 4
        ///
        ///else if @role_ID = 4 --rukovod
        ///	select r.*
        ///		,u.Name UserName
        ///	from RequestOP r
        ///		join [User] u on u.ID = r.User_ID
        ///		where exists [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Requests_In {
            get {
                return ResourceManager.GetString("Requests_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ResetSettings {
            get {
                object obj = ResourceManager.GetObject("ResetSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap switchtimescalesto_16x16 {
            get {
                object obj = ResourceManager.GetObject("switchtimescalesto_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap switchtimescalesto_32x32 {
            get {
                object obj = ResourceManager.GetObject("switchtimescalesto_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Upd60 {
            get {
                object obj = ResourceManager.GetObject("Upd60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
