//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.Zakup.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SC.Zakup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1C_SingleImport {
            get {
                object obj = ResourceManager.GetObject("1C_SingleImport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1С1 {
            get {
                object obj = ResourceManager.GetObject("1С1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addtext_32x32 {
            get {
                object obj = ResourceManager.GetObject("addtext_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap archive {
            get {
                object obj = ResourceManager.GetObject("archive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap belyj {
            get {
                object obj = ResourceManager.GetObject("belyj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage bo_order {
            get {
                object obj = ResourceManager.GetObject("bo_order", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage buynow {
            get {
                object obj = ResourceManager.GetObject("buynow", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clearfilter_16x16 {
            get {
                object obj = ResourceManager.GetObject("clearfilter_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clearfilter_32x32 {
            get {
                object obj = ResourceManager.GetObject("clearfilter_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage createpiechart {
            get {
                object obj = ResourceManager.GetObject("createpiechart", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit32 {
            get {
                object obj = ResourceManager.GetObject("edit32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage employeequickwelcome {
            get {
                object obj = ResourceManager.GetObject("employeequickwelcome", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap excel_icon1 {
            get {
                object obj = ResourceManager.GetObject("excel-icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FilterFromMe {
            get {
                object obj = ResourceManager.GetObject("FilterFromMe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FilterToMe {
            get {
                object obj = ResourceManager.GetObject("FilterToMe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap giphy_3 {
            get {
                object obj = ResourceManager.GetObject("giphy_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap greren {
            get {
                object obj = ResourceManager.GetObject("greren", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ide_16x16 {
            get {
                object obj = ResourceManager.GetObject("ide_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ide_32x32 {
            get {
                object obj = ResourceManager.GetObject("ide_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ignoremasterfilter_16x16 {
            get {
                object obj = ResourceManager.GetObject("ignoremasterfilter_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ignoremasterfilter_32x32 {
            get {
                object obj = ResourceManager.GetObject("ignoremasterfilter_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap In {
            get {
                object obj = ResourceManager.GetObject("In", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --declare @nakladId int = 1702;
        ///
        ///select case when exists(
        ///	select * from Nakladnaya n
        ///		join Nakladnaya from_n on from_n.FromObject_ID = n.Object_ID
        ///			and n.ID = @nakladId
        ///		join NakladLine from_nl on from_nl.Naklad_ID = from_n.ID
        ///		join NakladLine nl on nl.Naklad_ID = @nakladId
        ///			and nl.Postup_ID = from_nl.Postup_ID
        ///) then 1 else 0 end.
        /// </summary>
        internal static string IsSendNaklad {
            get {
                return ResourceManager.GetString("IsSendNaklad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --declare @nakladLineId int = 11060;
        ///
        ///select case when exists(
        ///	select * from NakladLine nl
        ///		join Nakladnaya n on nl.Naklad_ID = n.ID
        ///			and nl.ID = @nakladLineId
        ///		join Nakladnaya from_n on from_n.FromObject_ID = n.Object_ID
        ///		join NakladLine from_nl on from_nl.Naklad_ID = from_n.ID
        ///			and nl.Postup_ID = from_nl.Postup_ID
        ///) then 1 else 0 end.
        /// </summary>
        internal static string IsSendNakladeLine {
            get {
                return ResourceManager.GetString("IsSendNakladeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kpi_16x16 {
            get {
                object obj = ResourceManager.GetObject("kpi_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kpi_32x32 {
            get {
                object obj = ResourceManager.GetObject("kpi_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap merge_16x16 {
            get {
                object obj = ResourceManager.GetObject("merge_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap merge_32x32 {
            get {
                object obj = ResourceManager.GetObject("merge_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap merge_32x321 {
            get {
                object obj = ResourceManager.GetObject("merge_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap my {
            get {
                object obj = ResourceManager.GetObject("my", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --declare @nakladId int = 0
        ///
        ///select nl.*
        ///, n.DocDate
        ///, nom.Name Nomenkl
        ///, n.DocNumber Naklad
        ///, p.Measure
        ///, p.Category
        ///, p.Price
        ///, p.PriceAdditional
        ///, p.Quantity - p.QuantityMoved QuantityOnSklad
        ///, p.InventoryNum
        ///from NakladLine nl 
        ///	join Postupleniya p on p.ID = nl.Postup_ID						
        ///	join Nakladnaya n on nl.Naklad_ID = n.ID
        ///	left join Nomenklatura nom on p.Nomenkl_ID = nom.ID
        ///where Naklad_ID = @nakladId.
        /// </summary>
        internal static string NakladLines {
            get {
                return ResourceManager.GetString("NakladLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --declare @categories int = 0;
        ///--declare @start datetime = &apos;20200701&apos;;
        ///--declare @end datetime = &apos;20200801&apos;;
        ///
        ///with postup as(
        ///	select p.ID
        ///		,l.Naklad_ID
        ///		,p.Price * l.Quantity Cost
        ///		,p.PriceAdditional * l.Quantity CostAdditional
        ///		,p.Kontragent
        ///		,p.Organization
        ///	from Postupleniya p
        ///		join NakladLine l on l.Postup_ID = p.ID
        ///	where p.Category in (@categories)
        ///)
        ///
        ///select n.*
        ///	,from_p.Name FromProjectName
        ///	,(case when n.FromObject_ID is null then null
        ///		  else from_o.Name + &apos; - &apos; + from_o. [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Naklads {
            get {
                return ResourceManager.GetString("Naklads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap New {
            get {
                object obj = ResourceManager.GetObject("New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new2 {
            get {
                object obj = ResourceManager.GetObject("new2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage neworder {
            get {
                object obj = ResourceManager.GetObject("neworder", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noMy {
            get {
                object obj = ResourceManager.GetObject("noMy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --declare @projectIds int = 124;
        ///--declare @start datetime = &apos;20200401&apos;;
        ///--declare @end datetime = &apos;20200501&apos;;
        ///--declare @firmaId int = 1;
        ///
        ///with send as (
        ///	select l.Postup_ID
        ///		, n.FromObject_ID
        ///		, sum(l.Quantity) Quantity
        ///	from Nakladnaya n join NakladLine l on n.ID = l.Naklad_ID
        ///		join Postupleniya p on p.ID = l.Postup_ID
        ///	where isnull(FromObject_ID, 0) &gt; 0
        ///	group by l.Postup_ID, n.FromObject_ID
        ///),
        ///objs as (
        ///	select &apos;Object &apos; + CAST(obj.ID AS nvarchar)  ViewModelID
        ///		,&apos;Project &apos; + CAST(ob [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ObjectProjectTree {
            get {
                return ResourceManager.GetString("ObjectProjectTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select o.*
        ///,s.Nomer Schet_Nomer
        ///,s.NomerInternal Schet_NomerInternal
        ///,d.ID Detail_ID
        ///,d.Name DetailName
        ///,f.ID Firma_ID
        ///,f.Name FirmaName
        ///,su.ID Supplier_ID
        ///,su.Name SupplierName
        ///from Oplata o
        ///	left join Scheta s on o.Schet_ID = s.ID
        ///	left join Detail d on s.Detail_ID = d.ID 
        ///	left join SCFirma f on s.Firma_ID = f.ID
        ///	left join Supplier su on s.Supplier_ID = su.ID
        ///order by Data desc.
        /// </summary>
        internal static string Oplatas {
            get {
                return ResourceManager.GetString("Oplatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Out {
            get {
                object obj = ResourceManager.GetObject("Out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap packageproduct_16x16 {
            get {
                object obj = ResourceManager.GetObject("packageproduct_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap packageproduct_32x32 {
            get {
                object obj = ResourceManager.GetObject("packageproduct_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paid {
            get {
                object obj = ResourceManager.GetObject("paid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage pieseries {
            get {
                object obj = ResourceManager.GetObject("pieseries", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --declare @projectIds int = 124;
        ///--declare @firmaId int = 1;
        ///
        ///select p.*
        ///	,nom.Name Nomenkl
        ///	,Quantity - QuantityMoved QuantityOnSklad
        ///	,s.Project_ID Project_ID
        ///	,s.Firma_ID
        ///from Postupleniya p 
        ///	left join Scheta s on s.Nomer = p.Schet
        ///	left join Nomenklatura nom on p.Nomenkl_ID = nom.ID
        ///where p.Quantity - p.QuantityMoved &gt; 0
        ///	and p.IsDeleted = 0
        ///	and (@firmaId is null or s.Firma_ID = @firmaId)
        ///	--and exists (select * from Scheta s 
        ///	--			where s.Nomer = p.Schet and s.Project_ID in (@projectI [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Postupleniya {
            get {
                return ResourceManager.GetString("Postupleniya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap project_16x16 {
            get {
                object obj = ResourceManager.GetObject("project_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap project_32x32 {
            get {
                object obj = ResourceManager.GetObject("project_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red {
            get {
                object obj = ResourceManager.GetObject("red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ResetSettings {
            get {
                object obj = ResourceManager.GetObject("ResetSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sales_16x16 {
            get {
                object obj = ResourceManager.GetObject("sales_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sales_32x32 {
            get {
                object obj = ResourceManager.GetObject("sales_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save1 {
            get {
                object obj = ResourceManager.GetObject("save1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCAS_DemoCover {
            get {
                object obj = ResourceManager.GetObject("SCAS_DemoCover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCAS_DemoCover1 {
            get {
                object obj = ResourceManager.GetObject("SCAS_DemoCover1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage shipment {
            get {
                object obj = ResourceManager.GetObject("shipment", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage shopping_shoppingcart {
            get {
                object obj = ResourceManager.GetObject("shopping_shoppingcart", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --declare @objectId int = 1110;
        ///
        ///with send as (
        ///	select l.Postup_ID
        ///		, sum(l.Quantity) Quantity
        ///	from Nakladnaya n join NakladLine l on n.ID = l.Naklad_ID
        ///		join Postupleniya p on p.ID = l.Postup_ID
        ///	where FromObject_ID = @objectId
        ///	group by l.Postup_ID
        ///)
        ///select l.ID
        ///	, l.Postup_ID
        ///	, l.Naklad_ID
        ///	, n.DocDate
        ///	, nom.Name Nomenkl
        ///	, n.DocNumber Naklad
        ///	, p.Price
        ///	, p.PriceAdditional
        ///	, p.Measure
        ///	, l.InventoryNum
        ///	, p.Category
        ///	, p.Comment
        ///	, l.Quantity - isnull(send.Quantity, 0) Quant [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Sklad {
            get {
                return ResourceManager.GetString("Sklad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sklad_icon {
            get {
                object obj = ResourceManager.GetObject("sklad_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --declare @objectId int = 1110;
        ///--declare @start datetime = &apos;20200401&apos;;
        ///--declare @end datetime = &apos;20200501&apos;;
        ///
        ///with send as (
        ///	select l.Postup_ID
        ///		, sum(l.Quantity) Quantity
        ///	from Nakladnaya n join NakladLine l on n.ID = l.Naklad_ID
        ///		join Postupleniya p on p.ID = l.Postup_ID
        ///	where FromObject_ID = @objectId
        ///	group by l.Postup_ID
        ///)
        ///, lines as (
        ///	select l.ID
        ///	,l.Postup_ID
        ///	,l.Naklad_ID
        ///	,n.DocDate
        ///	,nom.Name Nomenkl
        ///	,n.DocNumber Naklad
        ///	,p.Price
        ///	,p.PriceAdditional
        ///	,p.Measure
        ///	,l.Inv [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string SkladGrouping {
            get {
                return ResourceManager.GetString("SkladGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap switchtimescalesto_16x16 {
            get {
                object obj = ResourceManager.GetObject("switchtimescalesto_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap switchtimescalesto_32x32 {
            get {
                object obj = ResourceManager.GetObject("switchtimescalesto_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Update {
            get {
                object obj = ResourceManager.GetObject("Update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update2 {
            get {
                object obj = ResourceManager.GetObject("update2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --declare @postupId int = 12629;
        ///
        ///update Postupleniya 
        ///set QuantityMoved = (select SUM(nl.Quantity)
        ///					from NakladLine nl
        ///						join Nakladnaya n on nl.Naklad_ID = n.ID
        ///							and n.FromObject_ID is null
        ///					where Postup_ID = @postupId
        ///					group by Postup_ID)
        ///where ID = @postupId.
        /// </summary>
        internal static string UpdateQuantityMoved {
            get {
                return ResourceManager.GetString("UpdateQuantityMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xls {
            get {
                object obj = ResourceManager.GetObject("xls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XlsDn {
            get {
                object obj = ResourceManager.GetObject("XlsDn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XlsUp {
            get {
                object obj = ResourceManager.GetObject("XlsUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yelow {
            get {
                object obj = ResourceManager.GetObject("yelow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YelowOrWhite {
            get {
                object obj = ResourceManager.GetObject("YelowOrWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Аренда {
            get {
                object obj = ResourceManager.GetObject("Аренда", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Загрузка_из_1С {
            get {
                object obj = ResourceManager.GetObject("Загрузка из 1С", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Инвентарь {
            get {
                object obj = ResourceManager.GetObject("Инвентарь", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap лампочка_вкл {
            get {
                object obj = ResourceManager.GetObject("лампочка вкл", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap лампочка_выкл {
            get {
                object obj = ResourceManager.GetObject("лампочка выкл", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap лампочка_крест__2_ {
            get {
                object obj = ResourceManager.GetObject("лампочка крест (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap НетФильтра {
            get {
                object obj = ResourceManager.GetObject("НетФильтра", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ОсновныеСредства {
            get {
                object obj = ResourceManager.GetObject("ОсновныеСредства", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Товар {
            get {
                object obj = ResourceManager.GetObject("Товар", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Услуга {
            get {
                object obj = ResourceManager.GetObject("Услуга", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
